"""add_whatsapp_broadcasts

Revision ID: 9cfa4c705540
Revises: 313079ff8b00
Create Date: 2026-05-25 14:48:28.806538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cfa4c705540'
down_revision: Union[str, Sequence[str], None] = '313079ff8b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['college_id'], ['colleges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broadcasts_id'), 'broadcasts', ['id'], unique=False)
    op.add_column('chat_logs', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('wa_phone_number_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'colleges', ['wa_phone_number_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'colleges', type_='unique')
    op.drop_column('colleges', 'wa_phone_number_id')
    op.drop_column('chat_logs', 'channel')
    op.drop_index(op.f('ix_broadcasts_id'), table_name='broadcasts')
    op.drop_table('broadcasts')
    # ### end Alembic commands ###
